### PR TITLE
Add @react-native-community/masked-view

### PR DESCRIPTION
**Pull request by LcTwisk**

### CODE REVIEW

**Comment by deepueg** [comment]
Can you also add a manifest entry pls ?

**Review by friederbluemle — APPROVED** [review]
Thanks @LcTwisk :+1:

**Comment by LcTwisk** [comment]
Thanks for adding the manifest entry @friederbluemle  🙇‍♂️ 
Just wondering, where is the `manifest.json` being used for? It looks like all worked fine without the entry 🤔

**Comment by friederbluemle** [comment]
> Just wondering, where is the manifest.json being used for? It looks like all worked fine without the entry 🤔

The manifest entry is used for the `ern add <dependency>` command, which checks the manifest to determine the version of the dependency to add (i.e. what it passes down to `yarn add ..`). Yes, a plain `yarn add ..` will work just fine in most cases.

When you have more than one miniapp in a container, the versions of dependencies (with native modules dependencies) need to be aligned - So having this thin `ern add ..` abstraction in place can help. Plus, it's possible a major update to the layout of library makes it incompatible with the existing plugin config, so it sort of provides a stable base version (known to work). You can still change/update it separately in each miniapp after testing.

**Pull request merged**
