### PR TITLE
Update react-native to 0.63.4 in dev manifest

### PR DESCRIPTION
**Pull request by friederbluemle**

### CODE REVIEW

**Review by belemaire — COMMENTED** [review]
I haven't yet published react-native 0.63.4 AAR to [Maven Central](https://mvnrepository.com/artifact/com.walmartlabs.ern/react-native).
Will do that later on today and approve this PR once done.

**Review by belemaire — APPROVED** [review]

**Comment by friederbluemle** [comment]
Awesome thanks! :+1:

**Comment by friederbluemle** [comment]
Somehow I don't see it yet.. Will wait with the merge.
https://mvnrepository.com/artifact/com.walmartlabs.ern/react-native

**Comment by belemaire** [comment]
@friederbluemle It's been published. You can see it here in main repo https://repo1.maven.org/maven2/com/walmartlabs/ern/react-native/0.63.4/
Still doesn't appear on the other website, shouldn't have given this url, it's some non official website and it looks like they don't have immediate refresh from central.

**Comment by friederbluemle** [comment]
🤦 My bad. Thanks. This is the search url on maven.org:
https://search.maven.org/artifact/com.walmartlabs.ern/react-native

**Pull request merged**
