### PR TITLE
Add react-native-fbads

### PR DESCRIPTION
**Pull request by ozcanzaferayan**

### CODE REVIEW

**Comment by friederbluemle** [comment]
Thanks @ozcanzaferayan - Curious: Which version of ern were you using locally to generate this plugin?

```
ern --version
```

**Comment by ozcanzaferayan** [comment]
Hi @friederbluemle, im using this versions:
ℹ electrode-native: 1.1.1
ℹ ern platform: 1000.0.0

**Comment by ozcanzaferayan** [comment]
I made changes for backward compability in ios  config

**Review by friederbluemle — APPROVED** [review]
Thanks @ozcanzaferayan :+1:

**Comment by friederbluemle** [comment]
Did you test this with the latest version of `react-native-fbads`? Or a specific version?

**Comment by friederbluemle** [comment]
Based on the folder name I'm assuming 7.0.5 - Just a few minor updates as a follow up here: #230

**Comment by ozcanzaferayan** [comment]
> Did you test this with the latest version of `react-native-fbads`? Or a specific version?

Yes i tested with latest fbads version. Thx so much.

**Pull request merged**
