### PR TITLE
React Native 61+ support

### PR DESCRIPTION
**Pull request by belemaire**
This PR adds new Electrode Native `0.41.0+` directory, which comes with support for React Native versions `0.61.x` and `0.62.x` introduced in https://github.com/electrode-io/electrode-native/pull/1542

It's basically a duplicate of all plugin configurations, adding an extra empty `react-native@>=0.61.0` configuration to most iOS plugin configurations as they don't need any specific plugin configuration when used with versions of React Native >=0.61.0 (thanks to cocoapods auto linking). 
Notable exceptions to this rule are :

- `react-native-electrode-bridge` which does not expose a podspec file (and didn't unfortunately looked straigtforward to create one, so this will be done separately by our iOS engineers), so we still inject it "the old way" in the Container.

- `react-native-photo-view` plugin does not declare an empty `react-native@>=0.61.0` configuration, but it declares a `podspec` file, as this plugin is not maintained anymore and does not have a `podspec` file associated with it.

Also updates all versions of native modules / react-native / react to latest applicable for dev `ern` platform version.

### CODE REVIEW

**Comment by belemaire** [comment]
Thanks for your review @friederbluemle 

1. I had to add it manually because while the podspec indeed appears in the git repo, it is not present in the [latest package version of this module (1.5.2)](https://registry.npmjs.org/react-native-photo-view/-/react-native-photo-view-1.5.2.tgz) ... This is not made clear because unfortunately there is no git tags in the repo / no release and no changelog :(

2. At first I thought there wasn't but actually your comment made me rethink things...
We could instead do the opposite, and have all current plugin config directives on iOS wrapped in a `react-native@<0.61.0` key. This way we don't have to define an empty one for `react-native@>=0.61.0`.
This won't remove the need to have all the plugins added to `ern_v0.41.0+` as the dynamic react native version keys was introduce in this version and older versions would fail if encountering such structure, but at least we won't have to define an empty `react-native@>=0.61.0` key in all plugins.

**Comment by friederbluemle** [comment]
> 1. I had to add it manually because while the podspec indeed appears in the git repo, it is not present in the [latest package version of this module (1.5.2)](https://registry.npmjs.org/react-native-photo-view/-/react-native-photo-view-1.5.2.tgz) ... This is not made clear because unfortunately there is no git tags in the repo / no release and no changelog :(

Okay makes sense. I only briefly checked the repo. 1.5.2 was released `2017-09-27T18:09:07.508Z` and the [podspec file was added](https://github.com/alwx/react-native-photo-view/commits/master/react-native-photo-view.podspec) on Feb 18 2018. That explains why.


> 2\. At first I thought there wasn't but actually your comment made me rethink things...
>     We could instead do the opposite, and have all current plugin config directives on iOS wrapped in a `react-native@<0.61.0` key. This way we don't have to define an empty one for `react-native@>=0.61.0`.
>     This won't remove the need to have all the plugins added to `ern_v0.41.0+` as the dynamic react native version keys was introduced in this version and older versions would fail if encountering such structure, but at least we won't have to define an empty `react-native@>=0.61.0` key in all plugins.

Hmm okay that's interesting. But what I really meant is: If the core platform "knows" it's working with a newer version of RN (one that uses CocoaPods), can't it _ignore_ the existing `copy`, `pbxproj` etc sections from the plugin config?

**Comment by belemaire** [comment]
> Hmm okay that's interesting. But what I really meant is: If the core platform "knows" it's working with a newer version of RN (one that uses CocoaPods), can't it ignore the existing copy, pbxproj etc sections from the plugin config?

Unfortunately not at this point. These directives can still prove to be of use in some context (for example our own bridge does not have a podspec yet and it seems complex to create one as it contains some swift mixed with objc code and requires a bridging header, wasn't able to achieve that yet). Also some more generic directives such as `copy` or `applyPatch` / `replaceInFile` could still be of use in some cases. And it makes it not possible to selectively only discard the `pbxproj` ones because all ios pre RN61 plugin configurations are making use of these directives so we would consider them incorrectly post RN61 if we keep the same config without doing any changes. It's either discarding them all or none.
I don't really see a different way right now, other than the one introduced :(

**Comment by friederbluemle** [comment]
Yes, I see the problem with bridge, and how _individual_ projects may require special casing..

I guess my main concern here is the introduction of a new _variable_ **key** `react-native@>=0.61.0` (or `react-native@<0.61.0`), as well as duplication of **a lot** of existing plugin configuration code. Obviously you have looked into this in much greater detail, so what I'm suggesting might not be possible, at least easily. Please correct me.

Basically, what I was hoping we could achieve is something like this:

We can safely assume that _most_ (current) React Native libraries are compatible with RN 0.60+ (which is when autolinking was first introduced: [CocoaPods by default](https://reactnative.dev/blog/2019/07/03/version-60#cocoapods-by-default), July 2019).

With a leaner approach, only **one added line** will be required for each plugin config that does **not** support CocoaPods autolinking, for example the `react-native-electrode-bridge` plugin:

### Before

```json
{
  "ios": {
    "copy": [
      { "source": "ios/ElectrodeReactNativeBridge/*", "dest": "{{{projectName}}}/ElectrodeReactNativeBridge" }
    ],
    "otherfields": "..."
  }
}
```

### After

```json
{
  "ios": {
    "requiresManualLinking": true,
    "copy": [
      { "source": "ios/ElectrodeReactNativeBridge/*", "dest": "{{{projectName}}}/ElectrodeReactNativeBridge" }
    ],
    "otherfields": "..."
  }
}
```

- ERN <0.41 would not know about and ignore the new `requiresManualLinking` key
- ERN >=0.41 (which understands CocoaPods) would process ios plugins under the assumption that the library is compatible, **unless** `requiresManualLinking` is set to `true` (in which case it would fall back to the old processing).

A mechanism like that would mean:

1. No modification to the manifest (other than updating the version numbers, and adding a new key to select plugins)
2. No code duplication/copying into a new folder `ern_v0.41.0+`
3. No nesting of existing ios config with a variable key

**Comment by belemaire** [comment]
Yes that's food for thoughts. I think something could be achieved by mixing what you suggest while also keeping new keys to dynamically select a configuration or another based on a react native version or version range (will explain why we should keep that -or not- in a sec).

Basically, what we could do is introduce your new suggested config directive `requiresManualLinking` which would be useful for our current bridge case (and potentially other fringe cases), that still require manual linking as of now even with RN61+.

Now we have some plugins for which we need to make use of new `podfile` / `extraPods` / `podspec` directives (`react-native-photo-view` only here in this manifest, and a couple others in our override manifests). In this case, we could just add these directives in current plugin configuration files. If the plugin configuration does not have `requiresManualLinking`, but has `podfile` / `extraPods` / `podspec`, and version of RN used is >= 61 (and ern >= 0.41.0) then ern will only consider these directives in the config, excluding all other ones (so this means that in terms of changes to current manifest, we can completely trash the new `ern_v0.41.0+` directory I created and just add `requiresManualLinking` to existing bridge plugin config and `podspec` to `react-native-photo-view` existing config.

Now finally, what if we want to keep support of existing generic directives such as `applyPatch` / `copy` / `replaceInFile` ... even for RN61+ ? We could just use `requiresManualLinking` which will consider these directives (but not really manual linking here, just wants ern to consider these directives in an RN61+ config, so maybe just only a rename of `requiresManualLinking` to something different such as `processAllDirectives` or whatever). This way we could just have the <RN61 config in a "react-native@<=0.61.0" object and the "react-native@>0.61.0" config with only `applyPatch` or some generic directives needed with a `processAllDirectives` directive. 
Another solution would be to not have such react native version config keys ... this would keep things more simple. But then we say that on iOS if running a version >= 0.61.0, all directives by `podspec` / `extrapods` / `podfile` will be ignored (unless `requiresManualLinking` is set). This means losing all the generic directives, but these directives anyway could be done through a custom podspec file (which is just some ruby script ... so you could do anything you want there, including applying a patch or doing some minor string replacement) ... Might take down that road as it will keep things more simple overall.

Thanks a lot for the detailed analysis and thinking :+1:

**Comment by belemaire** [comment]
Will go with second approach, keeping `requiresManualLinking` new directive and ignoring all generic and pbxproj injection directives on iOS if the version of react native is >= 0.61.0, unless the `requiresManualLinking` flag is set. This way we will just have to update the configuration of two plugins, respectively `react-native-electrode-bridge` and `react-native-photo-view` and we can trash the `ern_v0.41.0+` directory. Working on the necessary on https://github.com/electrode-io/electrode-native/pull/1542, will also update this PR once done.

**Comment by friederbluemle** [comment]
Great, thanks @belemaire :+1:
Also, regarding renaming it to `processAllDirectives` like you suggested or something that is better suited: I think that makes sense. Will also give this another review once updated.

**Comment by belemaire** [comment]
Added `requiresManualLinking` support and got rid of dynamic react native version key support.
Updated logic in https://github.com/electrode-io/electrode-native/pull/1542
Only kept `ern_v0.41.0+` for `react-native` 61/62 injection configuration.
Added `requiresManualLinking` directive to existing bridge plugin configuration and added `podspec` directive to existing `react-native-photo-view` plugin configuration.

**Pull request merged**
