### PR TITLE
Add Apache License

### PR DESCRIPTION
**Pull request by gmbharath12**

### CODE REVIEW

**Comment by krunalsshah** [comment]
Hey, @gmbharath12 not sure why are we adding this license. If this is required, all the plugins would?

**Comment by gmbharath12** [comment]
@krunalsshah  This is just for the code push plugin that we do differently, Special case 📦 
As you know, whoever uses this plugin, this piece of code will be injected into container.

**Comment by friederbluemle** [comment]
Yes, in general we should avoid putting the default Xcode (and Android Studio!) generated file headers into source control (especially on an open source project).

**Comment by gmbharath12** [comment]
you mean, we should handle injecting these files into container differently ?

**Pull request merged**
