### PR TITLE
chore: move all the plugin configuration to ern_v0.30.0+

### PR DESCRIPTION
**Pull request by krunalsshah**
move currently supported plugin config directives to  ern_v0.34.0+

### CODE REVIEW

**Comment by belemaire** [comment]
Thanks :+1: Much needed.

**Comment by friederbluemle** [comment]
What's the reason we need this nested subfolder at all `ern_v0.34.0`?

**Comment by belemaire** [comment]
After discussing this one internally together (thanks @friederbluemle for raising meaningful concern), and thinking about it, it's not proper and incorrect to just flatten all plugin configuration in a single directory as it basically discard support of all versions of Electrode Native < 0.30 while also incorrectly exposing some plugin configuration that contains directive supported only from ern 0.33 or 0.34 to clients using 0.30+.
We should perform some cleanup for sure, but without breaking functionality. We should actually make sure that `0.14+` directory only contains plugins that are using the `permissions` directive on Android, `0.33+` directory only contains plugins that are using `setBuildSettings` directive on iOS and `0.34+` directory only contains plugins that are using the `replaceInFile` directive on Android (per the guidelines made more explicit in https://github.com/electrode-io/electrode-native-manifest/pull/142/files)

**Comment by friederbluemle** [comment]
Thanks for the explanation @belemaire 👍 - I agree and also think that there has to be a very strong reason to discontinue support for old versions. I'm sure a lot of thought went into the existing directory structure, and so far is has been working reasonably well.

**Pull request closed without merging**
